### ISSUE TITLE
SyncHandler not working as expected

### ISSUE THREAD

**Issue by NVentimiglia** [Azure/mobile-services-samples#63]
I am implementing a SyncHandler and it is not working as expected. I am implementing a SyncHandler and it is not working as expected.  In short, it seems to get into a strange step where both insert and update operations fail, resulting in Conflict results.

Here is my code. It is based off of the official example [here] (https://github.com/Azure/mobile-services-samples/blob/master/TodoOffline/WindowsUniversal/TodoOffline/TodoOffline.Shared/SyncHandler.cs). 

`````
  public virtual async Task<JObject> ExecuteTableOperationAsync(IMobileServiceTableOperation operation)
        {
            MobileServiceInvalidOperationException error = null;

            do
            {
                error = null;

                try
                {
                    //First try
                    var result = await operation.ExecuteAsync();
                    return result;
                }
                catch (MobileServiceConflictException ex)
                {
                    error = ex;
                    Console.WriteLine("SyncHandler : "+ ex.Message);
                }
                catch (MobileServicePreconditionFailedException ex)
                {
                    error = ex;
                    Console.WriteLine("SyncHandler : " + ex.Message);
                }
                
                if (error != null)
                {
                    var localItem = operation.Item.ToObject<EntityBase>();
                    var serverValue = error.Value;
                    if (serverValue == null)
                    {
                        // 409 doesn't return the server item
                        serverValue = await operation.Table.LookupAsync(localItem.Id) as JObject;
                    }
                    
                    // Overwrite the server version and try the operation again by continuing the loop
                    operation.Item[MobileServiceSystemColumns.Version] = serverValue[MobileServiceSystemColumns.Version];
                    if (error is MobileServiceConflictException)
                    {
                        // change operation from Insert to Update
                        await operation.Table.UpdateAsync(operation.Item);
                    }
                }
            } while (error != null);

            return null;
        }
`````

Replication Steps

1) I create multiple records and begin to sync.
2) I kill my sync in the middle of the transaction
3) I close the app
4) I reopen the app
5) SyncHandler kicks in and catches a conflict
6) The 'serverValue' is null (not returned in the 409)
7) The Handler converts the operation to update
8) The second operation fails with another Conflict exception

How can I fix this ?

**Comment by lindydonna** [comment]
Fixed in e66e724. Try the sample again.

**Comment by NVentimiglia** [comment]
This is still an issue. Unable to sync at all as the app gets in an infinite loop. I have tried the new sample code. Here is my latest.

`````
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.MobileServices;
using Microsoft.WindowsAzure.MobileServices.Sync;
using Newtonsoft.Json.Linq;

    class SyncHandler : IMobileServiceSyncHandler
    {
        public static int counter;
        public virtual Task OnPushCompleteAsync(MobileServicePushCompletionResult result)
        {
            return Task.FromResult(0);
        }

        public virtual async Task<JObject> ExecuteTableOperationAsync(IMobileServiceTableOperation operation)
        {
            MobileServiceInvalidOperationException error = null;
            Func<Task<JObject>> tryOperation = operation.ExecuteAsync;

            do
            {
                error = null;

                try
                {
                    //First try
                    JObject result = await tryOperation();
                    return result;
                }
                catch (MobileServiceConflictException ex)
                {
                    error = ex;
                }
                catch (MobileServicePreconditionFailedException ex)
                {
                    error = ex;
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e.ToString());
                    throw e;
                }

                if (error != null)
                {
                    var localItem = operation.Item;

                    var serverValue = error.Value;
                    if (serverValue == null)
                    {
                        if (error is MobileServiceConflictException)
                        {
                            // change operation from Insert to Update
                            tryOperation = async () => await operation.Table.UpdateAsync(operation.Item) as JObject;
                        }
                    }
                    else
                    {
                        // 409 doesn't return the server item
                        serverValue = await operation.Table.LookupAsync(localItem[MobileServiceSystemColumns.Id]) as JObject;

                        // Overwrite the server version and try the operation again by continuing the loop
                        operation.Item[MobileServiceSystemColumns.Version] = serverValue[MobileServiceSystemColumns.Version];
                        if (error is MobileServiceConflictException)
                        {
                            // change operation from Insert to Update
                            tryOperation = async () => await operation.Table.UpdateAsync(operation.Item) as JObject;
                        }
                    }



                    continue;
                }
            } while (error != null);

            return null;
        }
    }
`````

**Comment by NVentimiglia** [comment]
http://i.imgur.com/TcczorS.gif

**Comment by NVentimiglia** [comment]
Serverside error log

2016-02-02T15:29:00  PID[8144] Information Message='The operation failed due to a conflict: 'Violation of PRIMARY KEY constraint 'PK_agdata.UploadResources'. Cannot insert duplicate key in object 'agdata.UploadResources'. The duplicate key value is (067704da-cc1b-4245-8986-fc5371c23289).
The statement has been terminated.'.', Id=47c7ac25-33e1-4457-86cc-11471e9da538, Category='App.Controllers.Tables'
2016-02-02T15:29:00  PID[8144] Verbose     Info - The operation failed due to a conflict: 'Violation of PRIMARY KEY constraint 'PK_agdata.UploadResources'. Cannot insert duplicate key in object 'agdata.UploadResources'. The duplicate key value is (067704da-cc1b-4245-8986-fc5371c23289).
The statement has been terminated.'. - App.Controllers.Tables - Tue Feb 02 2016, 15:29:00 PM
2016-02-02T15:29:00  PID[8144] Warning     Message='UserMessage='The operation failed due to a conflict: 'Violation of PRIMARY KEY constraint 'PK_agdata.UploadResources'. Cannot insert duplicate key in object 'agdata.UploadResources'. The duplicate key value is (067704da-cc1b-4245-8986-fc5371c23289).
The statement has been terminated.'.'', Status=409 (Conflict), Exception=System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Microsoft.WindowsAzure.Mobile.Service.Tables.EntityUtils.<SubmitChangesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Mobile.Service.EntityDomainManager`1.<UpdateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Mobile.Service.EntityDomainManager`1.<UpdateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Mobile.Service.TableController`1.<PatchAsync>d__12.MoveNext(), Id=47c7ac25-33e1-4457-86cc-11471e9da538, Category='App.Controllers.Tables'
